'''
Created on 23 Oct 2013

@author: michael
'''
EVENT_REPEAT_CHOICE_DOES_NOT_REPEAT = 0
EVENT_REPEAT_CHOICE_DAILY = 1
EVENT_REPEAT_CHOICE_WEEKDAYS = 2
EVENT_REPEAT_CHOICE_WEEKENDS = 3
EVENT_REPEAT_CHOICE_WEEKLY = 4
EVENT_REPEAT_CHOICE_MONTHLY_BY_DAY_OF_MONTH = 5

EVENT_REPEAT_CHOICES = (
    (EVENT_REPEAT_CHOICE_DOES_NOT_REPEAT, 'Does Not Repeat'),
    (EVENT_REPEAT_CHOICE_DAILY, 'Daily'),
    (EVENT_REPEAT_CHOICE_WEEKDAYS, 'Weekdays'),
    (EVENT_REPEAT_CHOICE_WEEKENDS, 'Weekends'),
    (EVENT_REPEAT_CHOICE_WEEKLY, 'Weekly'),
    (EVENT_REPEAT_CHOICE_MONTHLY_BY_DAY_OF_MONTH, 'Monthly By Day Of Month'),
)